#!/usr/bin/env bash
# Foliyo self-host installer — Node 22.5+ bundle from GitHub Releases.
set -euo pipefail

RELEASE_BASE="${FOLIYO_RELEASE_BASE:-https://github.com/foliyo-dev/foliyo/releases/latest/download}"
INSTALL_ROOT="${FOLIYO_HOME:-$HOME}"
CORE_DIR="${INSTALL_ROOT}/apps/foliyo"
DASHBOARD_DIR="${INSTALL_ROOT}/apps/dashboard"
DATA_DIR="${INSTALL_ROOT}/data"
LOG_DIR="${INSTALL_ROOT}/logs"
NGINX_OUT="${INSTALL_ROOT}/nginx-foliyo.conf"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

check_node() {
  if ! command -v node >/dev/null 2>&1; then
    echo "Node.js 22.5+ is required (built-in node:sqlite)." >&2
    echo "Install: https://nodejs.org/ or: curl -fsSL https://fnm.vercel.app/install | bash && fnm install 22" >&2
    exit 1
  fi
  # node:sqlite landed in 22.5
  if ! node -e "require('node:sqlite')" 2>/dev/null; then
    echo "Node $(node -v) cannot load node:sqlite. Upgrade to Node.js 22.5+." >&2
    exit 1
  fi
}

download() {
  local url="$1" dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$dest"
  else
    wget -q "$url" -O "$dest"
  fi
}

echo "Installing Foliyo (Node bundle)..."
check_node
need_cmd tar

mkdir -p "$CORE_DIR" "$DASHBOARD_DIR" "$DATA_DIR" "$LOG_DIR"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Downloading core bundle..."
if ! download "$RELEASE_BASE/foliyo-core.tar.gz" "$TMP/foliyo-core.tar.gz"; then
  echo "Release artifact not found: $RELEASE_BASE/foliyo-core.tar.gz" >&2
  echo "Build from source: git clone https://github.com/foliyo-dev/foliyo && make release" >&2
  exit 1
fi

echo "Downloading dashboard..."
download "$RELEASE_BASE/dashboard-build.tar.gz" "$TMP/dashboard.tar.gz"

rm -rf "${CORE_DIR:?}/"*
tar -xzf "$TMP/foliyo-core.tar.gz" -C "$CORE_DIR"
chmod +x "$CORE_DIR/foliyo"

# dashboard-build.tar.gz may contain a top-level build/ or flat static files
rm -rf "${DASHBOARD_DIR:?}/"*
mkdir -p "$DASHBOARD_DIR/build"
if tar -tzf "$TMP/dashboard.tar.gz" | head -1 | grep -q '^build/'; then
  tar -xzf "$TMP/dashboard.tar.gz" -C "$DASHBOARD_DIR"
else
  tar -xzf "$TMP/dashboard.tar.gz" -C "$DASHBOARD_DIR/build"
fi

# pqpm config
if [[ ! -f "${INSTALL_ROOT}/.pqpm.toml" ]]; then
  cat > "${INSTALL_ROOT}/.pqpm.toml" <<EOF
# Generated by Foliyo install.sh — edit secrets before first start
[service.foliyo]
command = "${CORE_DIR}/foliyo"
restart = "always"
max_memory = "1GB"
cpu_limit = "40%"
working_dir = "${INSTALL_ROOT}"
log_file = "${LOG_DIR}/foliyo.log"
env = {
  FOLIYO_PORT = "8080",
  FOLIYO_DB_DRIVER = "sqlite",
  FOLIYO_DB_PATH = "${DATA_DIR}/foliyo.db",
  FOLIYO_DATA_DIR = "${DATA_DIR}",
  FOLIYO_ASSETS_DIR = "${CORE_DIR}/assets",
  FOLIYO_MODE = "single",
  FOLIYO_SITE_URL = "https://yourdomain.com",
  FOLIYO_DASHBOARD_URL = "https://app.yourdomain.com",
  FOLIYO_ADMIN_EMAIL = "you@example.com",
  FOLIYO_ADMIN_PASSWORD = "change-me",
  NODE_ENV = "production"
}
EOF
  echo "Created ${INSTALL_ROOT}/.pqpm.toml — set FOLIYO_ADMIN_* and domain URLs."
fi

# nginx example with this install's paths
cat > "$NGINX_OUT" <<EOF
# Generated by Foliyo install.sh — copy into sites-available / Virtualmin
# app.yourdomain.com → dashboard (static)
server {
    listen 80;
    server_name app.yourdomain.com;
    root ${DASHBOARD_DIR}/build;
    index index.html;
    location / { try_files \$uri \$uri/ /index.html; }

    location ~ ^/(api|mesh)/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}

# yourdomain.com → public site (core)
server {
    listen 80;
    server_name yourdomain.com;
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_cache_valid 200 1h;
        add_header Cache-Control "public, max-age=3600";
    }
}
EOF

echo ""
echo "Foliyo installed."
echo "  Core:      ${CORE_DIR}/foliyo"
echo "  Dashboard: ${DASHBOARD_DIR}/build"
echo "  Data:      ${DATA_DIR}"
echo "  nginx:     ${NGINX_OUT}"
echo ""
echo "Next:"
echo "  1. Edit ${INSTALL_ROOT}/.pqpm.toml (admin email/password + site URLs)"
echo "  2. Install nginx config from ${NGINX_OUT} (replace yourdomain.com)"
echo "  3. pqpm start foliyo   # or: ${CORE_DIR}/foliyo"
echo ""
echo "Optional demo content (dev/marketing only):"
echo "  From a source checkout: make seed-demo"
echo "  Do not run seed-demo on a production self-host with real data."
